import jsPDF from 'jspdf';

interface SecurityReportData {
  projectName: string;
  periodDays: number;
  totalEvents: number;
  piiExposureRate: number;
  totalPiiDetections: number;
  injectionAttempts: number;
  injectionBlocked: number;
  redactionRate: number;
  topPiiTypes: { type: string; count: number }[];
}

export function generateSecurityReport(data: SecurityReportData): void {
  const doc = new jsPDF();
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  let y = 20;

  // Header
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Security Report', 20, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text(`Generated by LaunchPromptly  |  ${dateStr}  |  Last ${data.periodDays} days`, 20, y);
  doc.setTextColor(0);
  y += 15;

  // Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 20, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const summary = [
    `Project: ${data.projectName}`,
    `Reporting period: Last ${data.periodDays} days`,
    `Total events processed: ${data.totalEvents.toLocaleString()}`,
    `Report generated: ${now.toISOString()}`,
  ];
  summary.forEach((line) => {
    doc.text(line, 25, y);
    y += 6;
  });
  y += 8;

  // Guardrail Activity
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Guardrail Activity', 20, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const activity = [
    `PII Exposure Rate: ${data.piiExposureRate.toFixed(1)}%`,
    `Total PII Detections: ${data.totalPiiDetections.toLocaleString()}`,
    `Redaction Rate: ${data.redactionRate.toFixed(1)}%`,
    `Injection Attempts: ${data.injectionAttempts.toLocaleString()}`,
    `Injection Blocked: ${data.injectionBlocked.toLocaleString()}`,
    `Block Rate: ${data.injectionAttempts > 0 ? ((data.injectionBlocked / data.injectionAttempts) * 100).toFixed(1) : '0'}%`,
  ];
  activity.forEach((line) => {
    doc.text(line, 25, y);
    y += 6;
  });
  y += 8;

  // PII Types Breakdown
  if (data.topPiiTypes.length > 0) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('PII Types Detected', 20, y);
    y += 8;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    data.topPiiTypes.forEach((pii) => {
      doc.text(`${pii.type}: ${pii.count.toLocaleString()} detections`, 25, y);
      y += 6;
    });
    y += 8;
  }

  // Compliance Posture
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Compliance Posture', 20, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const compliance = [
    'Data processing: Client-side (SDK runs in your infrastructure)',
    'Data sent to dashboard: Metadata only (token counts, costs, guardrail types)',
    'PII handling: Detected and redacted before reaching LLM provider',
    'Encryption at rest: AES-256-GCM for sensitive fields',
    'Encryption in transit: HTTPS/TLS',
    'API key storage: bcrypt-hashed',
    'Data retention: Configurable per project (default 90 days)',
    'Telemetry: None — SDK makes no analytics or tracking calls',
  ];
  compliance.forEach((line) => {
    doc.text(line, 25, y);
    y += 6;
  });

  // Footer
  y = 280;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by LaunchPromptly — https://launchpromptly.com', 20, y);
  doc.text(`Report ID: ${crypto.randomUUID().slice(0, 8)}`, 160, y);

  // Save
  const filename = `security-report-${now.toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
